version: '3.8'

services:
  web:
    container_name: web
    image: cswcsm02/docker-web
    expose:
      - 8080
    ports:
      - 8080:8080

  nginx:
    container_name: nginx
    image: cswcsm02/docker-nginx
    ports:
      - 80:80
    depends_on:
      - web